name: opc
dependencies:
- python=3.6.6
- pip:
  - seaborn==0.9.0
  - fbprophet==0.5
  - xgboost==0.90
  - flask==1.0.3
  - scikit-learn==0.21.1
- numpy==0.4.3
- pandas==0.23.4
- nb_conda==2.2.1
- cython==0.29.7
- matplotlib==3.0.2
- scipy==1.2.0
- pystan==2.17.1.0